import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import StoreProvider from "@/redux/StoreProvider";
import { AudioPlayerProvider } from "./context/audio-player-context";
import LoginModal from "@/components/modals/LoginModal";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      {/* <AudioPlayerProvider> */}
        <html lang="en">
          <body className={inter.className}>
            {children}
            {/* <LoginModal/> */}
          </body>
        </html>
      {/* </AudioPlayerProvider> */}
    </StoreProvider>
  )
}